Fixes error due to malformed update call to update options for the deluged client. (#6427)
* fix: requirements.txt to reduce vulnerabilities (#6424)

The following vulnerabilities are fixed by pinning transitive dependencies:
- https://snyk.io/vuln/SNYK-PYTHON-MARKDOWN2-567097
- https://snyk.io/vuln/SNYK-PYTHON-MARKDOWN2-568905

* Fixes error due to malformed update call to update options for the
deluged client.

This fixes the following error:

ValueError: dictionary update sequence element #0 has length 13; 2 is required

* Fix update method for deluge client also

Co-authored-by: Snyk bot <github+bot@snyk.io>
Co-authored-by: miigotu <miigotu@gmail.com>