Fixes error due to malformed update call to update options for the deluged client.
This fixes the following error:

ValueError: dictionary update sequence element #0 has length 13; 2 is required